config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params[:id])
    if @flat.save
      flash[:success] = "Flat successfully created"
      redirect_to @flat
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

def update
  @flat = Flat.find(params[:id])
    if @flat.update(params[:id])
      flash[:success] = "Flat was successfully updated"
      redirect_to @flat
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
end

  
  def destroy
    @flat = Flat.find(params[:id])
    if @flat.destroy
      flash[:success] = 'Flat was successfully deleted.'
      redirect_to @flat
    else
      flash[:error] = 'Something went wrong'
      redirect_to @flat
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1><%=@flat.name%></h1>

<%= form_for(@flat) do |f| %>
  Name: <%= f.text_field :name %><br />
  Address: <%= f.text_field :address %><br />
  Description: <%= f.text_area :description %><br />
  Price: <%= f.number_field :price_per_night %><br />
  Guests: <%= f.number_field :number_of_guests %><br />
  <%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<h1>Flats</h1>
<ul>
  <% @flats.each do |flat| %>
    <li>
      <div class="card">
        <h3><%= flat.name %></h3>
        <p><%= flat.address %></p>
        <p>(°-°) <%= flat.number_of_guests %> - € <%= flat.price_per_night %></p>
      </div>
      <%= link_to "More info", flat_path(flat)%> <%= link_to "Edit", edit_flat_path(flat) %> <%= link_to "Remove", flats_path %>
    </li>
  <% end %>
</ul>

app/views/flats/new.html.erb
<div class="form">
  <h1>Add your own flat!</h1>

  <%= form_for(@flat) do |f| %>
    Name: <%= f.text_field :name %><br />
    Address: <%= f.text_field :address %><br />
    Description: <%= f.text_area :description %><br />
    Price: <%= f.number_field :price_per_night %><br />
    Guests: <%= f.number_field :number_of_guests %><br />
    <%= f.submit %>
  <% end %>
</div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<ul>
  <li><%= @flat.address %></li>
  <li><%= @flat.description %></li>
  <li><%= @flat.price_per_night %></li>
  <li><%= @flat.number_of_guests %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <div class="header">
    <p>Simple AirBnB</p>
    <%= link_to "Add flat", new_flat_path %>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>